databases:
  - name: smartroad-db
    databaseName: smartroad
    user: smartroad_user
    plan: free

services:
  - type: web
    name: smartroad-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: alembic upgrade head || true && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smartroad-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: CLOUDINARY_CLOUD_NAME
        value: dtlwfmuaq
      - key: CLOUDINARY_API_KEY
        value: "597324926383668"
      - key: CLOUDINARY_API_SECRET
        value: 4ayiXeY5hmUCSM33XCe5COFScv8
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM_NUMBER
        sync: false
      - key: ALERT_TO_NUMBER
        sync: false
