"""initial_migration

Revision ID: a1b2c3d4e5f6
Revises: 
Create Date: 2026-04-21 18:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('damage_type', sa.String(), nullable=False),
    sa.Column('severity_score', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_events_damage_type'), 'detection_events', ['damage_type'], unique=False)
    op.create_index(op.f('ix_detection_events_id'), 'detection_events', ['id'], unique=False)
    
    op.create_table('alert_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('alert_status', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['detection_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_logs_alert_status'), 'alert_logs', ['alert_status'], unique=False)
    op.create_index(op.f('ix_alert_logs_id'), 'alert_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_logs_id'), table_name='alert_logs')
    op.drop_index(op.f('ix_alert_logs_alert_status'), table_name='alert_logs')
    op.drop_table('alert_logs')
    op.drop_index(op.f('ix_detection_events_id'), table_name='detection_events')
    op.drop_index(op.f('ix_detection_events_damage_type'), table_name='detection_events')
    op.drop_table('detection_events')
    # ### end Alembic commands ###
